# Generated by Django 5.1 on 2024-10-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('anonymous', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('goal', models.IntegerField()),
                ('image', models.URLField()),
                ('Fund_type', models.TextField(choices=[('E', 'Equipment and Uniforms'), ('C', 'Competitions and Events'), ('F', 'Players Fees'), ('S', 'Coaching'), ('I', 'Club Infrastructure')])),
                ('is_open', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('member_only', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sportsclub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('club_size', models.TextField(choices=[('S', '< 10 Members'), ('M', '10-50 Members'), ('L', '50-120 Members'), ('XL', '>120 Members')])),
                ('club_location', models.TextField()),
                ('is_active', models.BooleanField()),
                ('club_logo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SportsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.TextField()),
            ],
        ),
    ]
