# Generated by Django 5.1 on 2024-10-22 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='supporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pledge',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='projects.project'),
        ),
        migrations.AddField(
            model_name='sportsclub',
            name='club_members',
            field=models.ManyToManyField(related_name='club_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sportsclub',
            name='club_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to='projects.sportsclub'),
        ),
        migrations.AddField(
            model_name='sportsclub',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clubs', to='projects.sportslist'),
        ),
    ]
