# Generated by Django 5.1 on 2024-10-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportslist',
            name='sport',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
