# Generated by Django 5.1 on 2024-10-24 23:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_sportslist_sport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsclub',
            name='club_members',
            field=models.ManyToManyField(blank=True, related_name='club_membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
