# Generated by Django 5.1 on 2024-09-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.TextField(choices=[('Individual', 'Individual'), ('Rescue', 'Rescue'), ('Community', 'Community')]),
        ),
    ]
