# Generated by Django 5.1 on 2024-10-25 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_sportsclub_club_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Fund_type',
            new_name='fund_type',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='owner',
            new_name='owner_club',
        ),
    ]
