# Generated by Django 5.1 on 2024-12-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_fund_type_project_fund_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsclub',
            name='club_logo',
            field=models.URLField(max_length=2000),
        ),
    ]
