# Generated by Django 5.1 on 2024-12-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_sportsclub_club_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsclub',
            name='club_logo',
            field=models.URLField(),
        ),
    ]
