# Generated by Django 5.1 on 2024-12-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_sportsclub_club_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='sportsclub',
            name='club_logo',
            field=models.URLField(max_length=2000),
        ),
    ]
